version: "3.9"
services:
  expert-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./expert:/usr/src/app/expert
      - ./data:/usr/src/app/data
    ports:
      - "5000:5000"
