FROM python:3-alpine

WORKDIR /usr/src/app

RUN pip install --user --no-warn-script-location pipenv

COPY . .

RUN python -m pipenv install

ENV FLASK_APP=expert
ENV FLASK_ENV=development
ENV FLASK_PORT=5000

EXPOSE 5000

CMD ["python", "-m", "pipenv", "run", "flask", "run", "--host=0.0.0.0"]
